### ISSUE TITLE
Running my host in GDB gives "uvwasi init failed"

### ISSUE THREAD

**Issue by Photosounder** [bytecodealliance/wasm-micro-runtime#2090]
Edit: It also happens when I launch the host by double-clicking the .exe file, so the only time the problem doesn't occur is when I launch the program from the MSYS2 command line.

I made a host in C that loads and executes a function from a WASM file, and everything works smoothly when I run the host outside of a debugger in the normal way, but not when I run the host in GDB in which case `wasm_runtime_instantiate()` fails with the error message `uvwasi init failed`. That's all it says, everything up to that point works correctly. So somehow running my host program in GDB makes "uvwasi init" fail.

To compile the host I use `clang version 15.0.7   Target: x86_64-w64-windows-gnu` (that's the MinGW64 version of clang) and GDB is `GNU gdb (GDB) 13.1` (also MinGW64's version of GDB).

Here's the relevant code up to the failure:

```
typedef struct
{
	wasm_module_t module;
	wasm_module_inst_t module_inst;
	wasm_exec_env_t exec_env;
	uint32_t stack_size, heap_size;
	char error_buf[128];
} wasm_ctx_t;

void native_print(wasm_exec_env_t exec_env, char *string)
{
	fprintf(stdout, "native_print(\"%s\") (pointer = 0x%08X)\n", string, string);
}

static NativeSymbol native_symbols[] = { { "native_print", native_print, "($)" } };

void wasm_host()
{
	static int init = 1;
	static wasm_ctx_t ctx = {0};

	if (init)
	{
		init = 0;

		ctx.stack_size = 256+40 + (1<<20);
		ctx.heap_size = 1024*1024+9 + (1<<20);

		// Init runtime
		if (!wasm_runtime_init())
		{
			fprintf(stderr, "Init runtime environment wasm_runtime_init() failed.\n");
			return;
		}

		// Register native functions
		if (!wasm_runtime_register_natives("env", native_symbols, sizeof(native_symbols) / sizeof(NativeSymbol)))
		{
			fprintf(stderr, "Register native functions wasm_runtime_register_natives() failed.\n");
			return;
		}

		// Load WASM file
		buffer_t wasm_buf = buf_load_raw_file("test.wasm");

		ctx.module = wasm_runtime_load(wasm_buf.buf, wasm_buf.len, ctx.error_buf, sizeof(ctx.error_buf));
		if (!ctx.module)
		{
			fprintf(stderr, "Load wasm module wasm_runtime_load() failed. error: %s\n", ctx.error_buf);
			return;
		}

		free_buf(&wasm_buf);

		// Create instance of WASM module
		ctx.module_inst = wasm_runtime_instantiate(ctx.module, ctx.stack_size, ctx.heap_size, ctx.error_buf, sizeof(ctx.error_buf));
		if (!ctx.module_inst)
		{
			fprintf(stderr, "Create instance of WASM module wasm_runtime_instantiate() failed. error: %s\n", ctx.error_buf);
			return;
		}
```

Host compilation command:
```
clang wasm_host.c rl.c -o wasm_host.exe -lwinmm -lcomdlg32 -lole32 -lOpengl32 -lShcore -lDbgHelp \
	-Wno-incompatible-pointer-types -Wno-dangling-else -Wno-parentheses -Wno-pointer-sign -Wno-shift-op-parentheses -Wno-tautological-pointer-compare \
	`sdl2-config --cflags --libs` \
	-I/d/VC_libs/include/ -I/home/lib/wasm-micro-runtime-main/core/iwasm/include \
	-L/d/VC_libs/lib/ -L/home/lib/wasm-micro-runtime-main/product-mini/platforms/windows/build \
	-O1 -g -llibiwasm
```

**Comment by wenyongh** [comment]
Hi, could you try setting wasi arguments after loading wasm module? Refer to:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/product-mini/platforms/posix/main.c#L695-L697

**Comment by Photosounder** [comment]
I added this but it didn't change anything:
```c
		// Set WASI args
#if WASM_ENABLE_LIBC_WASI != 0
		const char *dir_list[8] = { NULL };
		uint32 dir_list_size = 0;
		const char *env_list[8] = { NULL };
		uint32 env_list_size = 0;
		const char *argv[8] = { NULL };
		int argc = 0;
		wasm_runtime_set_wasi_args(ctx.module, dir_list, dir_list_size, NULL, 0,
                               env_list, env_list_size, argv, argc);
#endif
```

Maybe some of these values have to be set to something? My WASM file doesn't have an entry point of `main()` in case that matters.

**Comment by Photosounder** [comment]
I'd love to but GDB doesn't go into API functions, I'm not sure what I'm missing for it to happen. This is how I compiled (with MinGW64):

```
cd product-mini/platforms/windows/
rm -rf build 2>/dev/null; mkdir build && cd build
cmake .. -G"Unix Makefiles" -DWAMR_DISABLE_HW_BOUND_CHECK=1
cmake --build . --config Debug
```

**Comment by wenyongh** [comment]
I am not sure also, maybe you can add some `printf` in the uvwasi source code? Normally it is cloned under:
  `product-mini\platforms\windows\build\_deps\uvwasi-src`, the `unwasi_init` function is implemented in source file `src\uvwasi.c`

Refer to:
https://github.com/nodejs/uvwasi/blob/main/src/uvwasi.c#L235

**Comment by Photosounder** [comment]
In the meantime I tried with `-DWAMR_BUILD_LIBC_UVWASI=0`, and as before it works fine when launching the host from the command line, but when double-clicking the host or running it with GDB (same circumstances that caused the earlier failure) now I get `Lookup WASM function plugin_draw() with wasm_runtime_lookup_function() failed.`, which happens in my code right after the instantiation that previously failed:

```c
		// Create instance of WASM module
		ctx.module_inst = wasm_runtime_instantiate(ctx.module, ctx.stack_size, ctx.heap_size, ctx.error_buf, sizeof(ctx.error_buf));
		if (!ctx.module_inst)
		{
			fprintf(stderr, "Create instance of WASM module wasm_runtime_instantiate() failed. error: %s\n", ctx.error_buf);
			return;
		}

		// Lookup WASM function plugin_draw()
		func_plugin_draw = wasm_runtime_lookup_function(ctx.module_inst, "plugin_draw", NULL);
		if (!func_plugin_draw)
		{
			fprintf(stderr, "Lookup WASM function plugin_draw() with wasm_runtime_lookup_function() failed.\n");
			return;
		}
```

There must be something different, maybe related to environment variables, that changes between launching from the MinGW command line and launching from GDB or Windows Explorer.

**Comment by Photosounder** [comment]
Alright I was able to debug the library, turns out I needed to specify `-DCMAKE_BUILD_TYPE=Debug`. Seems like the problem has to do with detecting stdout as an unknown file type. Btw whoever wrote all this code needs to learn to use `fprintf(stderr, `  to report errors so we'd know what's going wrong more easily.
![2023-04-01 06 24 25](https://user-images.githubusercontent.com/7466235/229265572-7ceecb59-8346-48a3-aa20-778e87babe60.png)

**Comment by Photosounder** [comment]
I don't know how much testing you guys do on MinGW64, probably not very much, but I'm pretty sure this is a general problem so the MinGW64 version is unusable.

Here's the backtrace in case you might need it, don't worry about what `error_buf` says, that comes from looking for the `_start` function in a reactor:

```
#0  uvwasi__get_filetype_by_fd (fd=0, type=0x5f7d2f "")
    at C:/msys/home/lib/wasm-micro-runtime-main/product-mini/platforms/windows/build/_deps/uvwasi-src/src/uv_mapping.c:252
#1  0x00007ffde1b8ce9f in uvwasi__insert_stdio (uvwasi=0x76a1a60, table=0x769f860, fd=0, expected=0,
    name=0x7ffde1bbd890 "<stdin>")
    at C:/msys/home/lib/wasm-micro-runtime-main/product-mini/platforms/windows/build/_deps/uvwasi-src/src/fd_table.c:29
#2  0x00007ffde1b90af5 in uvwasi_fd_table_init (uvwasi=0x76a1a60, options=0x5f81e0)
    at C:/msys/home/lib/wasm-micro-runtime-main/product-mini/platforms/windows/build/_deps/uvwasi-src/src/fd_table.c:207
#3  0x00007ffde1b91bf9 in uvwasi_init (uvwasi=0x76a1a60, options=0x5f81e0)
    at C:/msys/home/lib/wasm-micro-runtime-main/product-mini/platforms/windows/build/_deps/uvwasi-src/src/uvwasi.c:331
#4  0x00007ffde1bb42fc in wasm_runtime_init_wasi (module_inst=0x76be8b0, dir_list=0x0, dir_count=0, map_dir_list=0x0,
    map_dir_count=0, env=0x0, env_count=0, addr_pool=0x0, addr_pool_size=0, ns_lookup_pool=0x0, ns_lookup_pool_size=0,
    argv=0x0, argc=0, stdinfd=0, stdoutfd=0, stderrfd=0,
    error_buf=0x7ff655d49240 <wasm_host[ctx]+32> "WASM module load failed: unknown import or incompatible import type",
    error_buf_size=128) at C:/msys/home/lib/wasm-micro-runtime-main/core/iwasm/common/wasm_runtime_common.c:3053
#5  0x00007ffde1b9fa4e in wasm_instantiate (module=0x76ca3e0, is_sub_inst=false, exec_env_main=0x0, stack_size=65536,
    heap_size=16777216,
    error_buf=0x7ff655d49240 <wasm_host[ctx]+32> "WASM module load failed: unknown import or incompatible import type",
    error_buf_size=128) at C:/msys/home/lib/wasm-micro-runtime-main/core/iwasm/interpreter/wasm_runtime.c:2084
#6  0x00007ffde1bb4442 in wasm_runtime_instantiate_internal (module=0x76ca3e0, is_sub_inst=false, exec_env_main=0x0,
    stack_size=65536, heap_size=16777216,
    error_buf=0x7ff655d49240 <wasm_host[ctx]+32> "WASM module load failed: unknown import or incompatible import type",
    error_buf_size=128) at C:/msys/home/lib/wasm-micro-runtime-main/core/iwasm/common/wasm_runtime_common.c:1205
#7  0x00007ffde1bb43db in wasm_runtime_instantiate (module=0x76ca3e0, stack_size=65536, heap_size=16777216,
    error_buf=0x7ff655d49240 <wasm_host[ctx]+32> "WASM module load failed: unknown import or incompatible import type",
    error_buf_size=128) at C:/msys/home/lib/wasm-micro-runtime-main/core/iwasm/common/wasm_runtime_common.c:1225
#8  0x00007ff655b8184a in wasm_host () at wasm_host.c:137
```
