### ISSUE TITLE
Wasm Loader: Double free error 

### ISSUE THREAD

**Issue by arjunr2** [bytecodealliance/wasm-micro-runtime#2288]
When loading the following compiled function in a module, I encounter a double free error. 
```(module
  (type (;0;) (func (param i32 i32)))
  (import "env" "memory" (memory (;0;) 2 1024 shared))
  (func $a_or (type 0) (param i32 i32)
    (local i32 i32 i32 i32 i32 i32 i32)
    global.get $__stack_pointer
    local.set 2
    i32.const 16
    local.set 3
    local.get 2
    local.get 3
    i32.sub
    local.set 4
    local.get 4
    local.get 0
    i32.store offset=12
    local.get 4
    local.get 1
    i32.store offset=8
    local.get 4
    i32.load offset=12
    local.set 5
    local.get 4
    i32.load offset=8
    local.set 6
    local.get 4
    local.get 6
    i32.store offset=4
    local.get 4
    i32.load offset=4
    local.set 7
    local.get 5
    local.get 7
    i32.atomic.rmw.or
    local.set 8
    local.get 4
    local.get 8
    i32.store
    return)
  (global $__stack_pointer (mut i32) (i32.const 71680))
  (export "memory" (memory 0))
)
```

Here is the encountered stack trace
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c62859 in __GI_abort () at abort.c:79
#2  0x00007ffff7ccd26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7df7298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7cd52fc in malloc_printerr (str=str@entry=0x7ffff7df9670 "double free or corruption (out)") at malloc.c:5347
#4  0x00007ffff7cd6fa0 in _int_free (av=0x7ffff7e2cb80 <main_arena>, p=0x5555555e64a0, have_lock=<optimized out>) at malloc.c:4314
#5  0x000055555556b8f4 in wasm_runtime_free_internal (ptr=0x5555555e64b0) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/common/wasm_memory.c:236
#6  0x000055555556b968 in wasm_runtime_free (ptr=0x5555555e64b0) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/common/wasm_memory.c:268
#7  0x00005555555b1499 in wasm_loader_ctx_destroy (ctx=0x5555555e6100) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_loader.c:5335
#8  0x00005555555baa33 in wasm_loader_prepare_bytecode (module=0x5555555e5d20, func=0x5555555e56c0, cur_func_idx=0, error_buf=0x7fffffffdb60 "", error_buf_size=128)
    at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_loader.c:10125
#9  0x00005555555aff73 in load_from_sections (module=0x5555555e5d20, sections=0x5555555e5eb0, is_load_from_file_buf=true, error_buf=0x7fffffffdb60 "", error_buf_size=128)
    at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_loader.c:3720
#10 0x00005555555b070e in load (buf=0x5555555e5c80 "", size=144, module=0x5555555e5d20, error_buf=0x7fffffffdb60 "", error_buf_size=128)
    at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_loader.c:4080
#11 0x00005555555b0a53 in wasm_loader_load (buf=0x5555555e5c80 "", size=144, main_module=true, error_buf=0x7fffffffdb60 "", error_buf_size=128)
    at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_loader.c:4247
#12 0x000055555557205e in wasm_load (buf=0x5555555e5c80 "", size=144, error_buf=0x7fffffffdb60 "", error_buf_size=128) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/interpreter/wasm_runtime.c:56
#13 0x000055555556d571 in wasm_runtime_load (buf=0x5555555e5c80 "", size=144, error_buf=0x7fffffffdb60 "", error_buf_size=128) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1120
#14 0x00005555555611fa in main (argc=1, argv=0x7fffffffdcf0) at /home/arjun/Documents/research/webassembly/wali/wasm-micro-runtime/product-mini/platforms/linux/../posix/main.c:926
```

**Comment by TianlongLiang** [comment]
Hi, the wast file you posted seems incomplete, could you please upload the wasm file?

**Comment by TianlongLiang** [comment]
Hi, [this pr](https://github.com/bytecodealliance/wasm-micro-runtime/pull/2295) should be able to fix this error. Thank you for spotting this issue, let me know if there are any other problems
