### ISSUE TITLE
nightly ci run is broken 

### ISSUE THREAD

**Issue by Zzzabiyaka** [bytecodealliance/wasm-micro-runtime#2493]
Nightly CI is broken because of the memory leak most likely introduced in 
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2483

CI job https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/5932720503

Trace:
```
      Start  5: Test_hello
 5/10 Test  #5: Test_hello .......................***Failed    0.33 sec

=================================================================
==2638==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0x7fbd91232808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5612d9afa56d in alloc_vector_data /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/shared/utils/bh_vector.c:19
    #2 0x5612d9afa56d in bh_vector_init /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/shared/utils/bh_vector.c:67
    #3 0x5612d9ade6f4 in wasm_byte_vec_new /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/iwasm/common/wasm_c_api.c:268
    #4 0x5612d9ae1f1c in wasm_module_validate /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/iwasm/common/wasm_c_api.c:2306
    #5 0x5612d9adda08 in main /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/samples/wasm-c-api/src/hello.c:68
    #6 0x7fbd90ddf082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fbd91232808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5612d9afa699 in bh_vector_init /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/shared/utils/bh_vector.c:78
    #2 0x5612d9ade6f4 in wasm_byte_vec_new /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/iwasm/common/wasm_c_api.c:268
    #3 0x5612d9ae1f1c in wasm_module_validate /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/iwasm/common/wasm_c_api.c:2306
    #4 0x5612d9adda08 in main /home/runner/work/wasm-micro-runtime/wasm-micro-runtime/samples/wasm-c-api/src/hello.c:68
    #5 0x7fbd90ddf082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

SUMMARY: AddressSanitizer: 87 byte(s) leaked in 2 allocation(s).
```

it's not only about CI build but we won't be able to merge some PRs until this is addressed, for example #2472 

cc @wenyongh @lum1n0us  for visibility

**Comment by wenyongh** [comment]
Thanks @Zzzabiyaka! I submitted #2498 to fix it.

**Comment by Zzzabiyaka** [comment]
Thank you. I will rebase my pr and check , if it's working I'll resolve the ticket
