### ISSUE TITLE
Segmentation Fault in wasm_interp_call_func_bytecode when running a valid Wasm module

### ISSUE THREAD

**Issue by khagankhan** [bytecodealliance/wasm-micro-runtime#3210]
## Describe the Bug

Running a valid test case on `iwasm` triggers a segmentation fault in `wasm_interp_call_func_bytecode` due to an invalid memory access.

`iwasm --version`: iwasm 1.3.2

`uname -a`:#62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## Steps to reproduce:

1. Save the `crash.wat` (Remove .txt extension)
2. Install and build WABT toolkit (`wat2wasm` from WABT can be used to convert `crash.wat` into `crash.wasm` using: `wat2wasm crash.wat -o crash.wasm`. I have also added `crash.wasm` that obviates the need to use `wat2wasm`)
3. Run `/path/to/iwasm crash.wasm`
4. Observe the `abort`.

## Files that cause the `abort`:
[crash.wat.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/14533620/crash.wat.txt)
[crash.wasm.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/14533621/crash.wasm.txt)

## Observed Behavior:
```
iwasm crash.wasm 

unhandled SIGSEGV, si_addr: 0x56473f5fa518
Aborted
```

## Expected behavior:
`iwasm` is supposed to run the module successfully. 

## GDB Backtrace

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555f0bef in wasm_interp_call_func_bytecode (module=0x5555558a4da0, exec_env=0x0, exec_env@entry=0x5555558a53e0, cur_func=0x5555558a3fb5, prev_frame=0xfffffffe, prev_frame@entry=0x5555558a5478) at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/interpreter/wasm_interp_fast.c:1658
1658	                        prev_frame->lp[ret_offset] =
(gdb) bt
#0  0x00005555555f0bef in wasm_interp_call_func_bytecode (module=0x5555558a4da0, exec_env=0x0, exec_env@entry=0x5555558a53e0, cur_func=0x5555558a3fb5, prev_frame=0xfffffffe, prev_frame@entry=0x5555558a5478)
    at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/interpreter/wasm_interp_fast.c:1658
#1  0x00005555555f4292 in wasm_interp_call_wasm (module_inst=module_inst@entry=0x5555558a4da0, exec_env=exec_env@entry=0x5555558a53e0, function=function@entry=0x5555558a3ad0, argc=<optimized out>, argc@entry=0, argv=argv@entry=0x7fffffffde70)
    at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/interpreter/wasm_interp_fast.c:6129
#2  0x000055555559277d in call_wasm_with_hw_bound_check (module_inst=module_inst@entry=0x5555558a4da0, exec_env=exec_env@entry=0x5555558a53e0, function=function@entry=0x5555558a3ad0, argc=argc@entry=0, argv=argv@entry=0x7fffffffde70)
    at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/interpreter/wasm_runtime.c:3103
#3  0x0000555555594f6f in wasm_call_function (exec_env=exec_env@entry=0x5555558a53e0, function=function@entry=0x5555558a3ad0, argc=argc@entry=0, argv=argv@entry=0x7fffffffde70)
    at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/interpreter/wasm_runtime.c:3175
#4  0x0000555555588c5b in wasm_runtime_call_wasm (exec_env=exec_env@entry=0x5555558a53e0, function=function@entry=0x5555558a3ad0, argc=argc@entry=0, argv=argv@entry=0x7fffffffde70)
    at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:2140
#5  0x0000555555581608 in execute_main (argv=<optimized out>, argc=<optimized out>, module_inst=0x7fffffffe210) at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/common/wasm_application.c:227
#6  wasm_application_execute_main (module_inst=module_inst@entry=0x5555558a4da0, argc=<optimized out>, argv=<optimized out>) at /users/khan22/wasmoi/targets/wasm-micro-runtime/core/iwasm/common/wasm_application.c:247
#7  0x000055555557c8f6 in app_instance_main (module_inst=0x5555558a4da0) at /users/khan22/wasmoi/targets/wasm-micro-runtime/product-mini/platforms/linux/../posix/main.c:119
#8  main (argc=<optimized out>, argv=<optimized out>) at /users/khan22/wasmoi/targets/wasm-micro-runtime/product-mini/platforms/linux/../posix/main.c:973
(gdb) exit

```

### Reduced code that caused the abort (`cat crash.wat`):

```
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param f64 f64 i32 f64 f32) (result i32)))
  (func (;0;) (type 0) (result i32)
    (local i32 i64 f32 f64)
    i32.const 385
    f64.const 0x1.9cbe6f8f163aap+9 (;=825.4877795084515;)
    f64.store offset=39 align=2
    f64.const 0x1.4530cd2e8aa6bp+8 (;=325.1906308258537;)
    i32.const 702
    f64.load offset=12 align=2
    local.tee 3
    local.get 3
    i64.reinterpret_f64
    i64.const 9218868437227405312
    i64.and
    i64.popcnt
    i64.const 11
    i64.eq
    select
    local.tee 3
    global.get 0
    i32.const 440
    i32.load16_u offset=58 align=1
    i32.const 178
    i32.load offset=16 align=2
    i32.and
    global.get 0
    f64.const 0x1.abf60cf2b5ea8p+8 (;=427.9611350721484;)
    i32.const 554
    f64.load offset=74 align=1
    local.tee 3
    local.get 3
    i64.reinterpret_f64
    i64.const 9218868437227405312
    i64.and
    i64.popcnt
    i64.const 11
    i64.eq
    select
    local.tee 3
    f64.min
    i32.const 758
    i32.load16_u offset=35 align=1
    i32.const 334
    i32.load16_s offset=81 align=1
    br_if 0 (;@0;)
    drop
    f32.const 0x1.bbacd6p+9 (;=887.3503;)
    i32.const 1
    call_indirect (type 1)
  )
  (func (;1;) (type 0) (result i32)
    i32.const 0
  )
  (func (;2;) (type 1) (param f64 f64 i32 f64 f32) (result i32)
    (local i32 i64 f32 f64 i32 i32)
    i32.const 86
    local.set 10
    i32.const 684
    i32.load8_s offset=77
    local.tee 2
    i32.const 0
    call_indirect (type 0)
    i32.xor
    local.set 9
    loop ;; label = @1
      local.get 9
      i32.const 561
      i64.load offset=74 align=4
      i32.const 183
      i64.load offset=94 align=2
      i64.eq
      i32.add
      local.set 9
      local.get 10
      i32.const -1
      i32.add
      local.tee 10
      br_if 0 (;@1;)
    end
    local.get 9
    local.get 2
    i32.extend8_s
    i32.rotr
  )
  (table (;0;) 2 funcref)
  (memory (;0;) 1)
  (global (;0;) (mut f64) f64.const -0x1.0035c4524daf8p+7 (;=-128.10501343916235;))
  (export "_main" (func 0))
  (elem (;0;) (i32.const 0) func 1 2)
)

```

## Additional information

A combination of AFL++ and Wasmlike, an Xsmith-based random program generator produced the snippet of code that found the issue. [Xsmith Project](https://www.flux.utah.edu/project/xsmith)

**Comment by wenyongh** [comment]
Close the issue since it was fixed with #3259.
