### ISSUE TITLE
clang asan Segmentation fault.

### ISSUE THREAD

**Issue by calvin2021y** [bytecodealliance/wasm-micro-runtime#3808]
build with in linux:

```sh
cmake -DWAMR_BUILD_SHARED=0 -DWAMR_BUILD_STATIC=1 -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_UVWASI=1 -DWAMR_BUILD_SIMD=1 -DWAMR_BUILD_EXCE_HANDLING=1 -DWAMR_BUILD_FAST_INTERP=0 -DWAMR_BUILD_PLATFORM=linux -DWAMR_BUILD_TARGET=X86_64
```

run with simple `fib.wat`

```wat
(module
  (func (export "fib") (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.add)
)
```

`wat2wasm fib.wat -o fib.wasm`

```sh
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:329
329	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
#0  __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:329
#1  0x0000555555601488 in b_memmove_s (s1=0x555555575a88, s1max=4, s2=0x555555575a89, n=3) at wamr/core/shared/utils/bh_common.c:115
#2  0x0000555555617430 in wasm_const_str_list_insert (str=0x555555575a89 "fib", len=3, module=0x555555e49010, is_load_from_file_buf=true, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_runtime.c:4757
#3  0x000055555561db05 in load_export_section (buf=0x555555575a87 "\001\003fib", buf_end=0x555555575a8e "\n\t\001\a", module=0x555555e49010, is_load_from_file_buf=true, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_loader.c:4122
#4  0x0000555555618497 in load_from_sections (module=0x555555e49010, sections=0x555555e48fe0, is_load_from_file_buf=true, wasm_binary_freeable=false, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_loader.c:5801
#5  0x0000555555619b00 in load (buf=0x555555575a70 "", size=41, module=0x555555e49010, wasm_binary_freeable=false, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_loader.c:6469
#6  0x00005555556198de in wasm_loader_load (buf=0x555555575a70 "", size=41, args=0x7fffffffc4c0, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_loader.c:6646
#7  0x0000555555613523 in wasm_load (buf=0x555555575a70 "", size=41, name=0x7fffffffc4c0, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/interpreter/wasm_runtime.c:65
#8  0x00005555555f4fae in wasm_runtime_load_ex (buf=0x555555575a70 "", size=41, args=0x7fffffffc4c0, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/common/wasm_runtime_common.c:1455
#9  0x00005555555f50d3 in wasm_runtime_load (buf=0x555555575a70 "", size=41, error_buf=0x7fffffffc578 "", error_buf_size=128) at wamr/core/iwasm/common/wasm_runtime_common.c:1492
```

**Comment by calvin2021y** [comment]
macOS same problem:

```sh
AddressSanitizer:DEADLYSIGNAL
=================================================================
==79721==ERROR: AddressSanitizer: BUS on unknown address (pc 0x00010108fcd5 bp 0x7ff7bfefb330 sp 0x7ff7bfefb330 T0)
==79721==The signal is caused by a WRITE memory access.
==79721==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x10108fcd5 in __sanitizer_internal_memmove sanitizer_libc.cpp:71
    #1 0x101071997 in __asan_memmove asan_interceptors_memintrinsics.cpp:71
    #2 0x1000ed5dc in b_memmove_s+0xac (tests_wamr.exe:x86_64+0x1000ed5dc)
    #3 0x1001a34e0 in wasm_const_str_list_insert+0xb0 (tests_wamr.exe:x86_64+0x1001a34e0)
    #4 0x1001534ec in load_export_section+0x66c (tests_wamr.exe:x86_64+0x1001534ec)
    #5 0x100142539 in load_from_sections+0x739 (tests_wamr.exe:x86_64+0x100142539)
    #6 0x10014852d in load+0x42d (tests_wamr.exe:x86_64+0x10014852d)
    #7 0x10014807f in wasm_loader_load+0xff (tests_wamr.exe:x86_64+0x10014807f)
    #8 0x100194f42 in wasm_load+0x32 (tests_wamr.exe:x86_64+0x100194f42)
    #9 0x10012bd84 in wasm_runtime_load_ex+0x114 (tests_wamr.exe:x86_64+0x10012bd84)
    #10 0x10012c0eb in wasm_runtime_load+0x10b (tests_wamr.exe:x86_64+0x10012c0eb)
```

**Comment by calvin2021y** [comment]
this error cause by wasm binary buffer is not clear, not wamr problem.
