### ISSUE TITLE
clang & windows build should use longjmp

### ISSUE THREAD

**Issue by calvin2021y** [bytecodealliance/wasm-micro-runtime#3809]
windows clang use setjmp like posix, the current implement only work for msvc.  

I guess for [mingw](https://github.com/mstorsjo/llvm-mingw) ,  BH_PLATFORM_WINDOWS also should be disabled.

```c
#if defined(__clang__) || defined(__GNUC__)
    #define os_thread_local_attribute __thread
#elif defined(_MSC_VER)
    #define os_thread_local_attribute __declspec(thread)
#else
    #error "Unknown compiler, unable to define os_thread_local_attribute"
#endif
```

**Comment by calvin2021y** [comment]
https://github.com/mstorsjo/llvm-mingw is great to cross build windows app.

**Comment by calvin2021y** [comment]
```diff
diff --git a/core/shared/platform/windows/shared_platform.cmake b/core/shared/platform/windows/shared_platform.cmake
index 502a8a2e..0b402a06 100644
--- a/core/shared/platform/windows/shared_platform.cmake
+++ b/core/shared/platform/windows/shared_platform.cmake
@@ -3,7 +3,10 @@
 
 set (PLATFORM_SHARED_DIR ${CMAKE_CURRENT_LIST_DIR})
 
-add_definitions(-DBH_PLATFORM_WINDOWS)
+if(NOT MINGW)
+  add_definitions(-DBH_PLATFORM_WINDOWS)
+endif()
+
 add_definitions(-DHAVE_STRUCT_TIMESPEC)
 add_definitions(-D_WINSOCK_DEPRECATED_NO_WARNINGS)

```

with this patch and some adjust I am able to build. 

without AOT it work as expect, with AOT it crashed.

```sh
=================================================================
==1564==ERROR: AddressSanitizer: access-violation on unknown address 0x12fb40490004 (pc 0x7ffee8ad46f8 bp 0x00cdb15ab370 sp 0x00cdb15ab2e8 T0)
==1564==The signal is caused by a WRITE memory access.                                                                                        
    #0 0x7ffee8ad46f7 in memset+0x77 (C:\Windows\SYSTEM32\ntdll.dll+0x1800a46f7)                                                              
    #1 0x7ffe8b672cc0 in _asan_memset+0x90 (C:\Users\admin\libclang_rt.asan_dynamic-x86_64.dll+0x180042cc0)                                   
    #2 0x7ff67678fed6  (C:\Users\admin\tests_wamr.exe+0x14020fed6)                                                                        
    #3 0x7ff676790a6d  (C:\Users\admin\tests_wamr.exe+0x140210a6d)                                                                        
    #4 0x7ff67671473c  (C:\Users\admin\tests_wamr.exe+0x14019473c)                                                                        
    #5 0x7ff6766a86ab  (C:\Users\admin\tests_wamr.exe+0x1401286ab)                                                                        
    #6 0x7ff67669e3cc  (C:\Users\admin\tests_wamr.exe+0x14011e3cc)                                                                        
    #7 0x7ff67669b61c  (C:\Users\admin\tests_wamr.exe+0x14011b61c)                                                                        
    #8 0x7ff6765f8991  (C:\Users\admin\tests_wamr.exe+0x140078991)                                                                        
    #9 0x7ff6765f8a23  (C:\Users\admin\tests_wamr.exe+0x140078a23)                                                                        
    #10 0x7ff6765da2b7  (C:\Users\admin\tests_wamr.exe+0x14005a2b7)                                                                       
    #11 0x7ff676581310  (C:\Users\admin\tests_wamr.exe+0x140001310)                                                                       
    #12 0x7ff676581365  (C:\Users\admin\tests_wamr.exe+0x140001365)                                                                       
    #13 0x7ffee8237373 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017373)                                             
    #14 0x7ffee8a7cc90 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18004cc90)                                                 
                                                                                                                                              
AddressSanitizer can not provide additional info.                                                                                             
SUMMARY: AddressSanitizer: access-violation (C:\Windows\SYSTEM32\ntdll.dll+0x1800a46f7) in memset+0x77                                        
==1564==ABORTING 
```

**Comment by calvin2021y** [comment]
```sh
=================================================================
==10248==ERROR: AddressSanitizer: access-violation on unknown address 0x126a940b0004 (pc 0x7ffee8ad46f8 bp 0x00e9ec1ab550 sp 0x00e9ec1ab4c8 T0)
==10248==The signal is caused by a WRITE memory access.                                                                                        
    #0 0x7ffee8ad46f7 in memset+0x77 (C:\Windows\SYSTEM32\ntdll.dll+0x1800a46f7)                                                               
    #1 0x7ffe8ed92cc0 in _asan_memset+0x90 (C:\Users\admin\libclang_rt.asan_dynamic-x86_64.dll+0x180042cc0)                                    
    #2 0x7ff79b1a2df6  (C:\Users\admin\tests_wamr.exe+0x140212df6)                                                                         
    #3 0x7ff79b1a398d  (C:\Users\admin\tests_wamr.exe+0x14021398d)                                                                         
    #4 0x7ff79b12718c  (C:\Users\admin\tests_wamr.exe+0x14019718c)                                                                         
    #5 0x7ff79b0c6d6b  (C:\Users\admin\tests_wamr.exe+0x140136d6b)                                                                         
    #6 0x7ff79b0bc7ec  (C:\Users\admin\tests_wamr.exe+0x14012c7ec)                                                                         
    #7 0x7ff79b0b9a3c  (C:\Users\admin\tests_wamr.exe+0x140129a3c)                                                                         
    #8 0x7ff79b008b21  (C:\Users\admin\tests_wamr.exe+0x140078b21)                                                                         
    #9 0x7ff79b008bb3  (C:\Users\admin\tests_wamr.exe+0x140078bb3)                                                                         
    #10 0x7ff79afea2b7  (C:\Users\admin\tests_wamr.exe+0x14005a2b7)                                                                        
    #11 0x7ff79af91310  (C:\Users\admin\tests_wamr.exe+0x140001310)                                                                        
    #12 0x7ff79af91365  (C:\Users\admin\tests_wamr.exe+0x140001365)                                                                        
    #13 0x7ffee8237373 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017373)                                              
    #14 0x7ffee8a7cc90 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18004cc90)    
```

**Comment by calvin2021y** [comment]
```sh
=================================================================
==10248==ERROR: AddressSanitizer: access-violation on unknown address 0x126a940b0004 (pc 0x7ffee8ad46f8 bp 0x00e9ec1ab550 sp 0x00e9ec1ab4c8 T0)
==10248==The signal is caused by a WRITE memory access.                                                                                        
    #0 0x7ffee8ad46f7 in memset+0x77 (C:\Windows\SYSTEM32\ntdll.dll+0x1800a46f7)                                                               
    #1 0x7ffe8ed92cc0 in _asan_memset+0x90 (C:\Users\admin\libclang_rt.asan_dynamic-x86_64.dll+0x180042cc0)                                    
    #2 0x7ff79b1a2df6  (C:\Users\admin\tests_wamr.exe+0x140212df6)  gc_init_internal
    #3 0x7ff79b1a398d  (C:\Users\admin\tests_wamr.exe+0x14021398d)  gc_init_with_struct_and_pool
    #4 0x7ff79b12718c  (C:\Users\admin\tests_wamr.exe+0x14019718c)  mem_allocator_create_with_struct_and_pool                                                  
    #5 0x7ff79b0c6d6b  (C:\Users\admin\tests_wamr.exe+0x140136d6b)  memory_instantiate                                                           
    #6 0x7ff79b0bc7ec  (C:\Users\admin\tests_wamr.exe+0x14012c7ec)  memories_instantiate                                         
    #7 0x7ff79b0b9a3c  (C:\Users\admin\tests_wamr.exe+0x140129a3c)  aot_instantiate                                                                       
    #8 0x7ff79b008b21  (C:\Users\admin\tests_wamr.exe+0x140078b21)  wasm_runtime_instantiate_internal                                                     
    #9 0x7ff79b008bb3  (C:\Users\admin\tests_wamr.exe+0x140078bb3)  wasm_runtime_instantiate                                                                      
    #10 0x7ff79afea2b7  (C:\Users\admin\tests_wamr.exe+0x14005a2b7)                                                                        
    #11 0x7ff79af91310  (C:\Users\admin\tests_wamr.exe+0x140001310)                                                                        
    #12 0x7ff79af91365  (C:\Users\admin\tests_wamr.exe+0x140001365)                                                                        
    #13 0x7ffee8237373 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017373)                                              
    #14 0x7ffee8a7cc90 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18004cc90)                                                  
                                                                                                                                               
AddressSanitizer can not provide additional info.                                                                                              
SUMMARY: AddressSanitizer: access-violation (C:\Windows\SYSTEM32\ntdll.dll+0x1800a46f7) in memset+0x77                                         
==10248==ABORTING 
```
